distributions:
  rmf-humble:
    url: https://raw.githubusercontent.com/open-rmf/rmf/humble/rmf.repos
    rosdistro_url: https://raw.githubusercontent.com/ros/rosdistro/master/humble/distribution.yaml
  rmf-jazzy:
    url: https://raw.githubusercontent.com/open-rmf/rmf/jazzy/rmf.repos
    rosdistro_url: https://raw.githubusercontent.com/ros/rosdistro/master/jazzy/distribution.yaml
  rmf-rolling:
    url: https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
    rosdistro_url: https://raw.githubusercontent.com/ros/rosdistro/master/rolling/distribution.yaml
